---
title: "ESP_106_project"
output: html_document
date: "2024-03-18"
Author: "Lucas Michel and Victoria Avalos"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir=".")
```

```{r}
# install.packages("tidyr")
# install.packages("ggplot2")
# install.packages("sf")
# install.packages("rnaturalearth")
# install.packages("rnaturalearthdata")
# install.packages("viridis")
# install.packages("raster")
# install.packages("cowplot")
# install.packages("dplyr")
# install.packages("tidyverse")
# install.packages("ggpmisc")
#install.packages("stringr")
```

```{r}
library(tidyr)
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(viridis)
library(raster)
library(cowplot)
library(dplyr)
library(tidyverse)
library(lubridate)
library(ggpmisc)
library(stringr)
```

```{r}
shape_data <- st_read("FWS_National_Regional_Boundaries/FWS_National_Regional_Boundaries.shp")

NorthEast <- read.csv("NorthEast.csv", skip = 3)
NorthWest_Pacific <- read.csv("NorthWest_Pacific.csv", skip = 3)
SouthEast <- read.csv("SouthEast.csv", skip = 3)
South_SouthWest <- read.csv("South_SouthWest.csv", skip = 3)
Northern_Rockies_Mountain <- read.csv("Northern_Rockies_Mountain.csv", skip = 3)
MidWestUpper <- read.csv("MidWestUpper.csv", skip = 3)
MidWestLower <- read.csv("MidWestLower.csv", skip = 3)
West_Pacific <- read.csv("West_Pacific.csv", skip = 3)

# Modify the 'Date' column for each dataset by first converting to a character string
NorthEast$Date <- as.integer(substr(as.character(NorthEast$Date), 1, 4))
NorthWest_Pacific$Date <- as.integer(substr(as.character(NorthWest_Pacific$Date), 1, 4))
SouthEast$Date <- as.integer(substr(as.character(SouthEast$Date), 1, 4))
South_SouthWest$Date <- as.integer(substr(as.character(South_SouthWest$Date), 1, 4))
Northern_Rockies_Mountain$Date <- as.integer(substr(as.character(Northern_Rockies_Mountain$Date), 1, 4))
MidWestUpper$Date <- as.integer(substr(as.character(MidWestUpper$Date), 1, 4))
MidWestLower$Date <- as.integer(substr(as.character(MidWestLower$Date), 1, 4))
West_Pacific$Date <- as.integer(substr(as.character(MidWestLower$Date), 1, 4))
```
```{r}
merged_Upper_Lower <- merge(MidWestUpper, MidWestLower, by = "Date", suffixes = c("_Upper", "_Lower"))

# Calculate the average of the "Value" column
merged_Upper_Lower$Value <- (merged_Upper_Lower$Value_Upper + merged_Upper_Lower$Value_Lower) / 2

# Create a new data frame with "Date" and averaged "Value" columns
MidWest <- merged_Upper_Lower[, c("Date", "Value")]
```



```{r}
NorthEast$Region <- "Northeast Region"
NorthWest_Pacific$Region <- "Pacific Region"
SouthEast$Region <- "Southeast Region"
South_SouthWest$Region <- "Southwest Region"
Northern_Rockies_Mountain$Region <- "Mountain Prairie Region"
MidWest$Region <- "Midwest Region"
West_Pacific$Region <- "Pacific Southwest Region"

# First, make sure your data is combined correctly
combined_Region_data <- bind_rows(NorthEast, NorthWest_Pacific, SouthEast, South_SouthWest, 
                                  Northern_Rockies_Mountain, MidWest, West_Pacific)

# Now pivot the data to long format
long_data_region <- combined_Region_data %>%
  pivot_longer(cols = -c(Region, Date), names_to = "Average Temp", values_to = "Value")

# Now pivot the long format data to wide format
combined_region_wide <- long_data_region %>%
  pivot_wider(names_from = Date, values_from = Value)

```

```{r}
# long_data_2 <- combined_Region_data %>%
#   pivot_longer(cols = -c(Region, Date), names_to = "Year", values_to = "Value") %>%
#   mutate(Year = as.integer(gsub("[^0-9]", "", Year))) %>% # Remove non-numeric characters before conversion
#   group_by(Region, Decade = cut(Year, breaks = seq(1885, 2035, by = 10), labels = seq(1890, 2030, by = 10))) %>%
#   summarise(AvgValue = mean(Value, na.rm = TRUE), .groups = 'drop')


```


```{r}
Region_Shape <- left_join(shape_data, combined_region_wide, by = c("REGNAME" = "Region"))

Region_Shape <- Region_Shape[-1, ]
```

```{r}
# year_periods <- list(c(1885, 1889), c(1890, 1899), c(1900, 1909), c(1910, 1919), 
#                      c(1920, 1929), c(1930, 1939), c(1940, 1949),
#                      c(1950, 1959), c(1960, 1969), c(1970, 1979), c(1980, 1989),
#                      c(1990, 1999), c(2000, 2009), c(2010, 2023))
# 
# 
# 
# # Assuming 'continent_temp' is your dataframe in R
# 
# for(period in year_periods) {
#   start_year <- period[1]
#   end_year <- period[2]
#   
#   # Select columns for the current period and calculate the mean
#   period_columns <- as.character(start_year:end_year)
#   Region_Shape[[paste0("Average_temp_", start_year, "_", end_year)]] <- rowMeans(Region_Shape[, period_columns, drop = FALSE], na.rm = TRUE)
#   
#   # Plot the graph for the current period
#   ggplot(Region_Shape, aes_string(x = "Region Index", y = paste0("Average_temp_", start_year, "_", end_year))) +
#     geom_line(aes(color = paste(start_year, "-", end_year))) +
#     geom_point(aes(color = paste(start_year, "-", end_year))) +
#     scale_color_manual(values = "blue") +
#     labs(title = paste("Temp (", start_year, "-", end_year, ")"),
#          x = "Region Index",
#          y = "Temp") +
#     theme_minimal() +
#     theme(legend.position = "bottom") +
#     geom_raster(aes(fill = paste0("Average_temp_", start_year, "_", end_year))) +
#     scale_fill_gradient(low = "blue", high = "red", name = "Temp") +
#     guides(fill = guide_colorbar(title = "Temp")) +
#     theme(legend.position = "right")
#   
#   # Note: Modify "Continent Index" to the actual column name representing continents if different.
# }

```

```{r}
#plot(Region_Shape$geometry, col=`Region_Shape$`2023`)

```

```{r}
#read in temp location data 
Temp_loco_47.5N_117.5W <- read.csv("temp location 1.csv", skip = 4)
Temp_loco_37.5N_117.5W <- read.csv("temp location 2.csv", skip = 4)
Temp_loco_42.5N_92.5W <- read.csv("temp location 3.csv", skip = 4)
Temp_loco_32.5N_102.5W <- read.csv("temp location 4.csv", skip = 4)
Temp_loco_42.5N_72.5W <- read.csv("temp location 5.csv", skip = 4)
Temp_loco_37.5N_102.5W <- read.csv("temp location 6.csv", skip = 4)
```

```{r}
# Function to extract coordinates from the file name and add as a new column
add_coordinates <- function(data, file_name) {
  # Extract coordinates using regular expressions
  coords <- str_extract(file_name, "\\d+\\.\\d+[N,S]\\_\\d+\\.\\d+[E,W]")
  coords <- gsub("N", " N", coords)
  coords <- gsub("W", " W", coords)
  coords <- gsub("S", " S", coords)
  coords <- gsub("E", " E", coords)
  coords <- gsub("_", ", ", coords)
  
  # Add the coordinates as a new column
  data <- data %>% mutate(Coordinates = coords)
  
  return(data)
}

# Apply the function to each dataframe
Temp_loco_47.5N_117.5W <- add_coordinates(Temp_loco_47.5N_117.5W, "Temp_loco_47.5N_117.5W")
Temp_loco_37.5N_117.5W <- add_coordinates(Temp_loco_37.5N_117.5W, "Temp_loco_37.5N_117.5W")
Temp_loco_42.5N_92.5W <- add_coordinates(Temp_loco_42.5N_92.5W, "Temp_loco_42.5N_92.5W")
Temp_loco_32.5N_102.5W <- add_coordinates(Temp_loco_32.5N_102.5W, "Temp_loco_32.5N_102.5W")
Temp_loco_42.5N_72.5W <- add_coordinates(Temp_loco_42.5N_72.5W, "Temp_loco_42.5N_72.5W")
Temp_loco_37.5N_102.5W <- add_coordinates(Temp_loco_37.5N_102.5W, "Temp_loco_37.5N_102.5W")


```

```{r}

combined_loco.data<- rbind(Temp_loco_32.5N_102.5W, Temp_loco_37.5N_117.5W, Temp_loco_37.5N_102.5W, Temp_loco_42.5N_72.5W, Temp_loco_42.5N_92.5W, Temp_loco_47.5N_117.5W)

combined.plot.temp<- ggplot(combined_loco.data, aes(x = Year, y = Anomaly, color = Coordinates)) +
  geom_line() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Anomalies Over Time",
       x = "Year",
       y = "Anomalie") +
  theme_minimal()
combined.plot.temp
```

```{r}
#Read in Precipitation data 

#Precip
#more ideal US Average volume of rain per year since 1900

Precip_data_2 <- read.csv("statistic_id504400_annual-precipitation-volume-in-the-united-states-1900-2023.csv", skip = 2)

head(Precip_data_2)


```


```{r}
precip_plot <- ggplot(Precip_data_2, aes(x = Year, y = Precipitation.Volume.in.Inches)) +
  geom_line() +  # Plot the precipitation data as a line
  geom_smooth(method = "lm", se = FALSE, color = "blue") +  # Add a linear trend line without the confidence interval shaded area
  labs(title = "Annual Precipitation Volume in the United States (1900-2023)",
       x = "Year",
       y = "Precipitation Volume (in inches)") +
  theme_minimal()  # Use a minimal theme for a clean look

# Print the plot
precip_plot
```


```{r}
# Fit a linear model to the data
linear_model <- lm(Precipitation.Volume.in.Inches ~ Year, data = Precip_data_2)

# Get the summary of the model to extract coefficients
model_summary <- summary(linear_model)

# Display the summary which includes the coefficients
print(model_summary)

# Alternatively, extract and print just the coefficients
coefficients <- coef(linear_model)
print(coefficients)

# The equation of the trend line is y = intercept + slope * x
intercept <- coefficients[1]
slope <- coefficients[2]
equation <- paste("y =", round(intercept, digits = 2), "+", round(slope, digits = 4), "* x")

# Print the equation of the trend line
print(equation)
```


```{r}
#read in the fire data

fire_data<- read.csv("Fire_Data.csv", skip = 1)
fire_data$Date <- as.Date(paste0(fire_data$Date, "01"), format = "%Y%m%d")

#remove 2024
fire_data_filtered <- fire_data %>%
  filter(format(Date, "%Y") != "2024")
head(fire_data_filtered)
```

```{r}
#Convert the 'Date' column to a character, extract the year, and convert it back to integer
fire_data_filtered <- fire_data_filtered %>%
  mutate(Year = as.integer(substr(as.character(Date), 1, 4)))

#Now aggregate the data by the 'Year' column
fire_data_summary <- fire_data_filtered %>%
  group_by(Year) %>%
  summarise(
    TotalFires = sum(Number.of.Fires, na.rm = TRUE),
    TotalAcresBurned = sum(Acres.Burned, na.rm = TRUE),
    AverageAcresPerFire = mean(Acres.Burned.per.Fire, na.rm = TRUE)
  )

#view the summarized data
head(fire_data_summary)

```


```{r}
#This is the plot for the Amount of fires burned each year 

fire.amount<- ggplot(fire_data_summary, aes(x = Year, y = TotalFires)) +
  geom_point() +
  geom_line(color = "blue") + 
   geom_smooth(method = "lm", se = FALSE, color = "hotpink")+ # Trend line
  labs(title = "Correlation between Year and Number of Fires Burned",
       x = "Year",
       y = "Number of Fires")
fire.amount

```

```{r}
# Fit a linear model to the data for the number of fires
linear_model_fire_amount <- lm(Number.of.Fires ~ Date, data = fire_data_filtered)

# Get the summary of the model to extract coefficients
model_summary_fire_amount <- summary(linear_model_fire_amount)

# Display the summary which includes the coefficients
print(model_summary_fire_amount)

# Extract and print just the coefficients
coefficients_fire_amount <- coef(linear_model_fire_amount)
print(coefficients_fire_amount)

# Convert Date to numeric since lm() treats Date objects differently
# Note: The slope will be per day; to convert to per year, divide by 365.25
intercept_fire_amount <- coefficients_fire_amount[1]
slope_fire_amount <- coefficients_fire_amount[2] # Adjust slope to per year
equation_fire_amount <- paste("y =", round(intercept_fire_amount, digits = 2), "+", round(slope_fire_amount, digits = 4), "* (Year - 2000)")

# Print the equation of the trend line
print(equation_fire_amount)

```


```{r}
#This is the data showing burned acres per fire 

fire.amount.per.fire<- ggplot(fire_data_summary, aes(x = Year, y = AverageAcresPerFire)) +
  geom_point() +            
  geom_line(color = "blue") + 
   geom_smooth(method = "lm", se = FALSE, color = "hotpink")+ # Trend line
  labs(title = "Correlation between Year and Acres Burned per Fire",
       x = "Year",
       y = "Acres Burned Per fire")
fire.amount.per.fire

```


```{r}
#Fit a linear model to the data
linear_model_per_fire <- lm(Acres.Burned.per.Fire ~ Date, data = fire_data_filtered)

#Get the summary of the model to extract coefficients
model_summary_per_fire <- summary(linear_model_per_fire)

#Display the summary which includes the coefficients
print(model_summary_per_fire)

#Alternatively, extract and print just the coefficients
coefficients_per_fire <- coef(linear_model_per_fire)
print(coefficients_per_fire)

#The equation of the trend line is y = intercept + slope * x
#Convert Date to numeric since lm() treats Date objects differently
intercept_per_fire <- coefficients_per_fire[1]
slope_per_fire <- coefficients_per_fire[2] # Adjust for slope per day to slope per year
equation_per_fire <- paste("y =", round(intercept_per_fire, digits = 2), "+", round(slope_per_fire, digits = 6), "* (Year - 2000)")

#Print the equation of the trend line
print(equation_per_fire)

```


```{r}
#Plotting the Acres Burned over the Years from the summarized data
plot.avg.fire <- ggplot(fire_data_summary, aes(x = Year, y = TotalAcresBurned)) +
  geom_point() +
  geom_line(color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "red") + # Trend line
  labs(title = "Correlation between Year and Acres Burned",
       x = "Year",
       y = "Acres Burned") +
  theme_minimal()

#Display the plot
plot.avg.fire
```
```{r}
#Assuming fire_data_filtered is already prepared
#Fit a linear model to the data
linear_model_fire <- lm(Acres.Burned ~ Date, data = fire_data_filtered)

#Get the summary of the model to extract coefficients
model_summary_fire <- summary(linear_model_fire)

#Display the summary which includes the coefficients
print(model_summary_fire)

#Alternatively, extract and print just the coefficients
coefficients_fire <- coef(linear_model_fire)
print(coefficients_fire)

#The equation of the trend line is y = intercept + slope * x
#Convert Date to numeric since lm() treats Date objects differently
intercept_fire <- coefficients_fire[1]
slope_fire <- coefficients_fire[2] # Adjust for slope per day to slope per year
equation_fire <- paste("y =", round(intercept_fire, digits = 2), "+", round(slope_fire, digits = 4), "* (Year - 2000)")

#Print the equation of the trend line
print(equation_fire)

```


```{r}
#This is the data showing burned acres per fire 

fire.amount.per.fire<- ggplot(fire_data_summary, aes(x = Year, y = AverageAcresPerFire)) +
  geom_point() +            
  geom_line(color = "blue") + 
   geom_smooth(method = "lm", se = FALSE, color = "hotpink")+ # Trend line
  labs(title = "Correlation between Year and Acres Burned per Fire",
       x = "Year",
       y = "Acres Burned Per fire")
fire.amount.per.fire

```

```{r}
#Assuming fire_data_filtered is already prepared
#Fit a linear model to the data
linear_model_fire <- lm(Acres.Burned ~ Date, data = fire_data_filtered)

#Get the summary of the model to extract coefficients
model_summary_fire <- summary(linear_model_fire)

#Display the summary which includes the coefficients
print(model_summary_fire)

#Alternatively, extract and print just the coefficients
coefficients_fire <- coef(linear_model_fire)
print(coefficients_fire)

#The equation of the trend line is y = intercept + slope * x
#Convert Date to numeric since lm() treats Date objects differently
intercept_fire <- coefficients_fire[1]
slope_fire <- coefficients_fire[2] # Adjust for slope per day to slope per year
equation_fire <- paste("y =", round(intercept_fire, digits = 2), "+", round(slope_fire, digits = 4), "* (Year - 2000)")

#Print the equation of the trend line
print(equation_fire)

```

```{r}
NOAA_Globe.file <- ("NOAAGlobalTemp_v6.0.0_gridded_s185001_e202401_c20240208T152650 (1).nc")

NOAA_Globe <- brick(NOAA_Globe.file)

NOAA_Globe_rotated <- rotate(NOAA_Globe)

rotated_NOAA_Globe <- extent(NOAA_Globe_rotated)
```

```{r}
plot(NOAA_Globe_rotated)
```

```{r}
plot(NOAA_Globe_rotated[[1]])
```

